version: '3'

services:

  mongo:
    image: mongo:3.4.24-xenial
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - /opt/mongo:/data/db
    ports:
      - 27017:27017
    # command: mongod --smallfiles --logpath=/dev/null # --quiet
    networks: 
      - default
      - my_docker_net

  mongo-express:
    image: mongo-express:0.49.0
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
    networks: 
      - default
      - my_docker_net

networks: 
  my_docker_net: 
    external: true 


